export const zhHans = {
  tabs: {
    library: '书库',
    data: '数据',
    excerpts: '摘录',
  },
  reader: {
    toc: '目录',
    search: '搜索',
    settings: '阅读设置',
    addBookmark: '添加当前书签',
    removeBookmark: '取消当前书签',
    controls: '阅读控制',
    close: '关闭阅读',
    cannotOpen: '无法打开这本书',
    returnToLibrary: '返回书库',
    excerpt: '摘录',
    excerptSelection: '摘录所选文字',
    dismissFootnote: '关闭脚注',
    dismissFootnoteHint: '关闭脚注弹窗',
  },
  search: {
    title: '在图书中搜索',
    results: '搜索结果',
    recent: '最近搜索',
    clear: '清除',
    field: '在此书中搜索',
    close: '关闭搜索',
    searching: '正在搜索…',
    recentEmpty: '最近的搜索会显示在这里',
    noResults: (query: string) => `没有找到“${query}”`,
    searchFor: (query: string) => `搜索 ${query}`,
  },
  settings: {
    title: '阅读设置',
    decreaseFont: '减小字号',
    increaseFont: '增大字号',
    pageTurnMode: '翻页模式',
    appearanceMode: '明暗模式',
    dissolve: '淡入淡出',
    light: '浅色',
    dark: '深色',
    lineHeight: '行间距',
    letterSpacing: '字符间距',
    pageMargin: '页边空白',
    reset: '恢复默认设置',
  },
  navigation: {
    bookmarks: '书签',
    bookmarkCount: (count: number) => `共 ${count} 个书签`,
    showBookmarks: '查看本书全部书签',
    returnToToc: '返回目录',
    unnamedLocation: '未命名位置',
    noToc: '没有可用目录',
    noBookmarks: '还没有书签',
    noBookmarksDetail: '阅读时点击书签按钮即可添加',
  },
  library: {
    title: '书库',
    reading: '阅读',
    bookCover: (title: string) => `${title}书封`,
  },
  data: {
    title: '数据',
    todayReading: '今天阅读',
    /** Data Tab Core B.3：今日阅读主卡标题与文案。 */
    todayReadingTitle: '今日阅读',
    todayCharsLabel: '阅读字数',
    characterUnit: '字',
    todaySummaryChars: (chars: number) => `今天你已经阅读了 ${chars} 字。`,
    todaySummaryExcerpts: (count: number) => `今天你记录了 ${count} 条摘录。`,
    todaySummaryDuration: (duration: string) => `今天你已阅读${duration}。`,
    todaySummaryZero: '开始阅读后，这里会显示你今天的阅读数据。',
    /**
     * Data Tab 视觉稿还原：今日阅读主卡状态词（纯时长档位，无评分无评价）。
     * 0 秒 → todayStatusZero；(0, 60) 秒 → todayStatusJustStarted；
     * [60, 1800) 秒 → todayStatusSteady；>= 1800 秒 → todayStatusDeep。
     */
    todayStatusZero: '今天还没读',
    todayStatusJustStarted: '刚开始',
    todayStatusSteady: '稳步进行',
    todayStatusDeep: '沉浸其中',
    /** 主卡三行指标标签（配色点）：时长 / 字数 / 摘录。 */
    todayMetricDuration: '时长',
    todayMetricChars: '字数',
    todayMetricExcerpts: '摘录',
    todaySummaryCharsAndExcerpts: (chars: number, count: number) =>
      `今天你已经阅读了 ${chars} 字，并记录了 ${count} 条摘录。`,
    /** 摘要 section 右侧链接（详情页未实现：纯展示，不可点）。 */
    showAll: '全部显示',
    /** 阅读节奏卡加粗结论（“最近 7 天”与界面 section 文案对齐）。 */
    rhythmSummaryRecent: (days: number) => `最近 7 天，你有 ${days} 天进行了阅读。`,
    totalExcerptLabel: '累计摘录',
    /** dayKey → 周几：new Date(y, m - 1, d).getDay() 取下标。 */
    weekdayNames: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    last7Days: '最近 7 天',
    totalReadingTime: '阅读时段',
    today: '今天',
    readingSpeed: '阅读速度',
    currentStreak: '连续阅读',
    totalReadingDays: '阅读天数',
    excerpts: '摘录',
    recentReading: '最近阅读',
    readingHabits: '阅读习惯',
    readingAccumulation: '阅读积累',
    readingActivity: '阅读活跃',
    overview: '阅读概览',
    summarySection: '摘要',
    readingRhythm: '阅读节奏',
    past7Days: '过去 7 天',
    activeDays: '活跃天数',
    currentHint: '当前',
    overviewSummary: (days: number) => `过去 7 天，你有 ${days} 天进行了阅读。`,
    overviewZero: '开始阅读后，这里会显示你的阅读节奏。',
    rhythmSummary: (duration: string) => `过去 7 天累计阅读${duration}。`,
    rhythmZero: '过去 7 天暂无阅读记录。',
    currentStreakHint: '当前连续',
    totalHint: '累计',
    dayUnit: '天',
    excerptUnit: '条',
    speedUnit: '字/分钟',
    minuteUnit: '分钟',
    hourUnit: '小时',
    lessThanOneMinute: '< 1 分钟',
    zeroMinutes: '0 分钟',
    moreThanAverage: (duration: string) => `比过去 7 天日均多 ${duration}`,
    lessThanAverage: (duration: string) => `比过去 7 天日均少 ${duration}`,
    aboutAverage: '与过去 7 天日均基本持平',
    startTracking: '开始记录你的阅读节奏',
    startReadingHint: '开始阅读后，这里会显示你的趋势',
    loadFailed: '暂时无法读取阅读数据',
    chartAccessibility: (parts: string) => `最近 7 天阅读时长，${parts}`,
  },
  debug: {
    readerEngine: '阅读引擎调试',
  },
  excerpts: {
    title: '摘录',
    today: '今天',
    yesterday: '昨天',
    past7Days: '过去7天',
    thisMonth: '本月',
    monthTitle: (year: number, month: number) => `${year}年${month}月`,
    emptyTitle: '还没有摘录',
    emptyHint: '阅读时选中文字，即可保存摘录或添加笔记。',
    /** Excerpts Tab Core E：books mode section header 右侧数量，如"12条"/"1条"。 */
    bookExcerptCount: (count: number) => `${count}条`,
    /**
     * Excerpts Tab Core E：books mode 无 chapterTitle 时的 Source 行文本。
     * section header 已是书名，这里只保住"返回原文"导航入口，不重复书名。
     */
    backToSource: '返回原文',
    /** 原生搜索框占位文案。 */
    searchPlaceholder: '搜索',
    /** 搜索无结果时的标题。 */
    searchEmptyTitle: '没有找到相关摘录',
    /** 搜索无结果时的提示。 */
    searchEmptyHint: '试试其他关键词',
  },
} as const;
