export const zhHans = {
  tabs: {
    library: '书库',
    data: '数据',
    excerpts: '摘录',
  },
  reader: {
    toc: '目录',
    search: '搜索',
    settings: '阅读设置',
    addBookmark: '添加当前书签',
    removeBookmark: '取消当前书签',
    controls: '阅读控制',
    close: '关闭阅读',
    cannotOpen: '无法打开这本书',
    returnToLibrary: '返回书库',
    excerpt: '摘录',
    excerptSelection: '摘录所选文字',
    dismissFootnote: '关闭脚注',
    dismissFootnoteHint: '关闭脚注弹窗',
  },
  search: {
    title: '在图书中搜索',
    results: '搜索结果',
    recent: '最近搜索',
    clear: '清除',
    field: '在此书中搜索',
    close: '关闭搜索',
    searching: '正在搜索…',
    recentEmpty: '最近的搜索会显示在这里',
    noResults: (query: string) => `没有找到“${query}”`,
    searchFor: (query: string) => `搜索 ${query}`,
  },
  settings: {
    title: '阅读设置',
    decreaseFont: '减小字号',
    increaseFont: '增大字号',
    pageTurnMode: '翻页模式',
    appearanceMode: '明暗模式',
    dissolve: '淡入淡出',
    light: '浅色',
    dark: '深色',
    lineHeight: '行间距',
    letterSpacing: '字符间距',
    pageMargin: '页边空白',
    colorTemp: '冷暖色调',
    colorTempNeutral: '标准',
    colorTempWarm: '暖',
    colorTempCool: '冷',
    reset: '恢复默认设置',
  },
  navigation: {
    bookmarks: '书签',
    bookmarkCount: (count: number) => `共 ${count} 个书签`,
    showBookmarks: '查看本书全部书签',
    returnToToc: '返回目录',
    unnamedLocation: '未命名位置',
    noToc: '没有可用目录',
    noBookmarks: '还没有书签',
    noBookmarksDetail: '阅读时点击书签按钮即可添加',
  },
  library: {
    title: '书库',
    reading: '阅读',
    bookCover: (title: string) => `${title}书封`,
    /** 书库三点菜单 → 备份与恢复。 */
    backupMenuItem: '备份与恢复',
    backupSheetTitle: '备份与恢复',
    exportBackup: '导出备份',
    importBackup: '导入备份',
    exportingBackup: '正在导出…',
    importingBackup: '正在导入…',
    exportBackupDone: (fileName: string) => `备份已生成：${fileName}`,
    importBackupDone: (bookCount: number) => `已恢复 ${bookCount} 本书的全部数据`,
    importBackupConfirmTitle: '导入备份？',
    importBackupConfirmMessage: '这会覆盖当前全部图书、阅读进度、高亮、摘录和统计数据，且无法撤销。',
    importBackupConfirm: '导入',
    cancel: '取消',
    ok: '好',
    /** 导入失败原因（BackupImportError.code → 文案）。 */
    backupErrorNotAReaderBackup: '这不是有效的阅读备份文件',
    backupErrorUnsupportedBackup: '备份文件版本太新，请先更新 App',
    backupErrorMissingDatabase: '备份文件中缺少数据库',
    backupErrorNotADatabase: '备份文件已损坏',
    backupErrorBackupFromNewerApp: '备份来自更新版本的 App，请先更新 App',
    backupErrorIncomplete: '备份文件不完整，当前书库未被替换',
    backupErrorGeneric: '备份失败，请重试',
  },
  data: {
    title: '数据',
    todayReading: '今天阅读',
    /** Data Tab Core B.3：今日阅读主卡标题与文案。 */
    todayReadingTitle: '今日阅读',
    characterUnit: '字',
    /** 主卡三行指标标签（配色点）：时长 / 字数 / 摘录。 */
    todayMetricDuration: '时长',
    todayMetricChars: '字数',
    todayMetricExcerpts: '摘录',
    /** 每日目标设置 Sheet。 */
    goalSheetTitle: '每日目标',
    goalDurationLabel: '阅读时长',
    goalCharsLabel: '阅读字数',
    goalExcerptsLabel: '摘录',
    /** 阅读节奏卡：7 日累计阅读时长的小标题。 */
    last7DaysTotalLabel: '最近 7 天累计阅读',
    totalExcerptLabel: '累计摘录',
    /** dayKey → 周几：new Date(y, m - 1, d).getDay() 取下标。 */
    weekdayNames: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    last7Days: '最近 7 天',
    totalReadingTime: '阅读时段',
    today: '今天',
    readingSpeed: '阅读速度',
    currentStreak: '连续阅读',
    totalReadingDays: '阅读天数',
    excerpts: '摘录',
    readingRhythm: '阅读节奏',
    past7Days: '过去 7 天',
    activeDays: '活跃天数',
    currentHint: '当前',
    totalHint: '累计',
    dayUnit: '天',
    excerptUnit: '条',
    speedUnit: '字/分钟',
    minuteUnit: '分钟',
    hourUnit: '小时',
    lessThanOneMinute: '< 1 分钟',
    zeroMinutes: '0 分钟',
    loadFailed: '暂时无法读取阅读数据',
    readingOverview: '阅读概览',
    dailyGoal: '目标已达成',
    previousWeek: '上一周',
    nextWeek: '下一周',
    hourlyDistribution: '当天阅读时长',
    peakHour: '最活跃的一个小时：',
    weeklySpeedRange: '本周每日阅读速度',
    noSpeedData: '当天暂无速度数据',
    speedRangeHint: '灰色区间是当天每分钟速度的第 10 至 90 百分位，圆点是所选日期的最新样本。',
    timeDetailHint: '每根柱子表示当天对应小时内的有效阅读时长。',
    speedRangeLabel: '最近 7 天速度范围',
    latestReadingSpeed: '最近一次记录',
    aboutMetric: (title: string) => `关于${title}`,
    aboutReadingTime: '阅读时段按设备本地时间归入每个小时，仅统计有效阅读会话。点击每日柱子可查看当天详情。',
    aboutReadingSpeed: '阅读速度以有效阅读的字数和时长计算。区间显示每天每分钟样本的第 10 至 90 百分位；点击某天可查看详情。',
    aboutReadingRhythm: '最近 7 天包含今天和之前 6 个本地日历日。连续阅读、累计阅读天数和摘录总数来自当前书库的阅读记录。',
    /** 每日详情页：日期切换。 */
    prevDay: '前一天',
    nextDay: '后一天',
  },
  excerpts: {
    title: '摘录',
    today: '今天',
    yesterday: '昨天',
    past7Days: '过去7天',
    thisMonth: '本月',
    monthTitle: (year: number, month: number) => `${year}年${month}月`,
    emptyTitle: '还没有摘录',
    emptyHint: '阅读时选中文字，即可保存摘录或添加笔记。',
    /**
     * Excerpts Tab Core E：books mode 无 chapterTitle 时的 Source 行文本。
     * section header 已是书名，这里只保住"返回原文"导航入口，不重复书名。
     */
    backToSource: '返回原文',
    /** 原生搜索框占位文案。 */
    searchPlaceholder: '搜索',
    /** 搜索无结果时的标题。 */
    searchEmptyTitle: '没有找到相关摘录',
    /** 搜索无结果时的提示。 */
    searchEmptyHint: '试试其他关键词',
  },
} as const;
